# ===============================
# Configuración básica del sitio
# ===============================
title: "Rolando Figueroa Bolivar"

url: "https://rolofigueroa.github.io"
baseurl: ""

# ===============================
# Tema
# ===============================
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

# ===============================
# Navegación superior
# ===============================
navigation:
  - title: "Inicio"
    url: /
  - title: "Sobre mí"
    url: /#sobre-mi
  - title: "Experiencia"
    url: /#experiencia
  - title: "Proyectos"
    url: /#proyectos
  - title: "Contacto"
    url: /#contacto
