# ===============================
# Información básica del sitio
# ===============================
title: "Rolando Figueroa Bolivar"
subtitle: "Electricidad Industrial · Ing. de Minas"


# ===============================
# Tema
# ===============================
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"   # luego puedes probar: dark, mint, contrast

plugins:
  - jekyll-include-cache

# ===============================
# Branding
# ===============================
logo: "/assets/img/profile.jpg"
masthead_title: "Rolando Figueroa Bolivar"


# ===============================
# Navegación superior
# ===============================
navigation:
  - title: "Inicio"
    url: /
  - title: "Sobre mí"
    url: /#sobre-mi
  - title: "Experiencia"
    url: /#experiencia
  - title: "Proyectos"
    url: /#proyectos
  - title: "Contacto"
    url: /#contacto

# ===============================
# Comportamiento por defecto
# ===============================
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      breadcrumbs: false
