title: "Rolando Figueroa Bolivar"
description: "Egresado de Electricidad Industrial (TECSUP) | Bachiller Ing. de Minas (UNSA) | Mantenimiento & Potencia"
theme: jekyll-theme-minimal

# (opcional pero recomendado)
logo: /assets/img/profile.jpg

# Links (para que el theme muestre “View my GitHub Profile” y otros)
github_username: rolofigueroa
